version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-contact-form"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ybuap0ws8a79"
s3_prefix = "lambda-contact-form"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
